### ISSUE TITLE
Make the configurations more readable.

### ISSUE THREAD

**Issue by Mxrcon** [emilyncosta/mtbseq-nf#19]
This task stems from https://github.com/emilyncosta/mtbseq-nf/pull/17#issuecomment-883365354

**Comment by abhi18av** [comment]
Then, let's try to use the following pattern

```nextflow
TBBWA {
// global params

// module params

// <- Here we add the module level params mentioned in tbbwa.nf file, which a user can override through a central location ->
resultsDir = "${params.outdir}/tbbwa"
saveMode = 'copy'
shouldPublish = true
}


```

I think that we're at a stage we can try some stuff out, I'd be curious to see how the `params.outdir` behaves within this context.

**Comment by abhi18av** [comment]
@Mxrcon , perhaps we can classify the changes mentioned https://github.com/emilyncosta/mtbseq-nf/issues/19#issuecomment-885039728 as part of pipeline params - what are you thoughts?

**Comment by Mxrcon** [comment]
Hmm, could be a task right? I agreed, the optional params acomodation still a great task

**Comment by abhi18av** [comment]
Agreed, I have create another task for params.

Closing this PR as the conf files are updated now.
