### ISSUE TITLE
Add basic structure to individual modules

### ISSUE THREAD

**Issue by Mxrcon** [emilyncosta/mtbseq-nf#4]
This task concerns with the addition of basic structure to individual modules.

**Comment by Mxrcon** [comment]
concluded by bb404c315544ff1dd907639e5a84ccb3b43d6a6c

**Comment by abhi18av** [comment]
@Mxrcon , on the right hand side of GH, there's a section called "Linked pull request" (I linked this issue as an example) - then you don't need to manually close the linked issue.

If PR is merged, it'll be closed by itself.

**Comment by abhi18av** [comment]
I'm re-opening this issue since the structure isn't there for individual modules.

A structure means, 

``` 

params

process def 

test 

```

**Comment by Mxrcon** [comment]
Ok, Thanks for pointing that, this pr still need a lot of work before get merged!
